spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:hopl}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:hopl}
    password: ${DB_PASSWORD:hopl}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration/postgresql
  h2:
    console:
      enabled: false
